### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [solusipse/ureq#1]
[Extra null pointer checks are not needed](http://pubs.opengroup.org/onlinepubs/9699919799/functions/free.html) in [a function like "ureq_close"](https://github.com/solusipse/ureq/blob/474acd62795b6167aed6f2dc7a14c23bfe5a7bfd/ureq.c#L517).

**Comment by solusipse** [comment]
That's very interesting, thank you! But I'm afraid that not every implementation of `free` deals with pointers in such manner. That's something I definitely need to check (I'm pretty sure I had some problems with it when using xtensa sdk).
