### ISSUE TITLE
Project restructuring...

### ISSUE THREAD

**Issue by RicoAntonioFelix** [solusipse/ureq#12]
I've taken the opportunity to make a major change in the structure of the project by introducing a more lean design, separating components of the system into their own file definitions ([details](https://github.com/solusipse/ureq/pull/11))...

Details that is irrelevant to the user of the system has been hidden in a directory (**`internal`**)...

All a user should be concerned with now is the files in the root directory and the examples folder...

I've also renamed the http methods to use a pattern suggested [here](https://github.com/solusipse/ureq/pull/5) which includes UREQ_*...

You can now take it from here if this proposal is accepted and introduce proper source documentation in the interface file **`ureq.h`** for each function to make the framework self explanatory by just looking at that single file...

**Comment by solusipse** [comment]
I just merged #11. Thank you!

**Comment by RicoAntonioFelix** [comment]
:crown:
