### ISSUE TITLE
Improve const-correctness

### ISSUE THREAD

**Issue by elfring** [solusipse/ureq#2]
I suggest to add the key word "const" to the type specifiers for parameters like the following.
- r (function "[ureq_get_header](https://github.com/solusipse/ureq/blob/af618774befba763114f7a01d9e26f4253d96d6d/ureq.h#L146)")
- return type (function "[ureq_get_code_description](https://github.com/solusipse/ureq/blob/af618774befba763114f7a01d9e26f4253d96d6d/ureq.h#L154)")

Would you like to apply the advices from [an article](https://en.wikipedia.org/w/index.php?title=Const_%28computer_programming%29#Consequences) to more places in your source files?

**Comment by RicoAntonioFelix** [comment]
This issue can be closed since it was rectified in the restructuring of the project...

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/RicoAntonioFelix/ureq/commit/2c70e414ee7a10abea91490f461d9ecc267a995c).

**Comment by RicoAntonioFelix** [comment]
No problem sir... :v:

**Comment by solusipse** [comment]
There were many changes addressing this issue (check pull requests by @RicoAntonioFelix), please point exact places where we need improvements or I'll close this issue.
