### ISSUE TITLE
Disparity between function pointer signatures...

### ISSUE THREAD

**Issue by RicoAntonioFelix** [solusipse/ureq#9]
`struct Page` is declared as follows:

``` c
struct Page {
    char *url;
    char *(*func)();
    char *method;
};
```

But  in function `ureq_serve` which adds a page to the list of pages, its parameter to initialize the function pointer in a page is as follows:
`char *(*func)(HttpRequest *)`...

Is this something that was overlooked?

If yes, then I can send a commit to fix the issue in my already submitted PR...

**Comment by solusipse** [comment]
Yes, that was overlooked, thanks for noticing. Please send such commit. Btw, awesome job with this pull request, many thanks!

**Comment by RicoAntonioFelix** [comment]
Upon closer reading of the `README.md` file I came to realize that it was declared that way to allow parsing `GET` parameters and working with `POST` data...

**Comment by solusipse** [comment]
It was declared that way so user could bind a function that does not take any parameters. But structure has changed a bit since then and  declaring `char *(*func)(struct HttpRequest *)` in `ureq.h` won't hurt now, I guess.

**Comment by RicoAntonioFelix** [comment]
It doesn't seem to cause any problem so I'll skip sending such a commit and ignore this issue for the moment...

Feel free to merge the PR at its current state if you so desire...
